changelog:
  categories:
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Bug fixes
      labels:
        - bug
        - bugfix
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Other changes
      labels:
        - '*'
  exclude:
    labels:
      - dependencies
      - chore
    authors:
      - github-actions[bot]
